### ISSUE TITLE
Wrong font on eastern Windows versions

### ISSUE THREAD

**Issue by PoByBolek** [PoByBolek/PmlUnit#2]
In his [pull request] @yang827 posted an image of PML Unit in Hull & Outfitting 12.1. Note that almost everything except for the summary and last test run labels uses a fixed width font. Nothing in the code base except for those two labels explicitly sets a font, so all controls should inherit the app's default font.

The other docked windows (Design Explorer and Command Window) also use that fixed width font for their title instead of the normal sans-serif font like the rest of the application.

Is this an issue with Hull & Outfitting or is the Chinese Windows version using a different default font? Should PML Unit explicitly set its default font during start up? (There are some stackoverflow posts about [default fonts in Windows Forms applications][stackoverflow].)

Besides the wrong font being selected, the labels above the test list should still be placed next to each other and not overlap like that.

![screenshot](https://user-images.githubusercontent.com/23608096/80788503-e841e800-8bbb-11ea-97e8-bd690cbe200f.PNG)

  [pull request]: https://github.com/PoByBolek/PmlUnit/pull/1
  [stackoverflow]: https://stackoverflow.com/questions/297701/default-font-for-windows-forms-application

**Comment by yang827** [comment]
This screenshot is taken from my laptop. I have a laptop with a 15 inch screen and 1920x1080 Resolution. The recommended scaling is 150% by default. There are many display errors in the Marine system. It will be fine when I set it to 100%.

![dpi](https://user-images.githubusercontent.com/23608096/81182620-9d233d00-8fe0-11ea-9692-654459e01b29.PNG)

**Comment by PoByBolek** [comment]
Hm.... I can't reproduce this at all. I tried setting the scaling to 150% on Windows 10 and Windows 7 but neither PDMS nor E3D experience these font issues that you have.

I created a [font-issue] branch with a "Debug Fonts..." label in the TestRunnerControl. On my machines, this outputs

>TestRunnerControl.Font = [Font: Name=Microsoft Sans Serif, Size=8,25, Units=3, GdiCharSet=0, GdiVerticalFont=False]
>TestRunnerControl.Parent....Font = [Font: Name=Microsoft Sans Serif, Size=8,25, Units=3, GdiCharSet=0, GdiVerticalFont=False]
>Control.DefaultFont = [Font: Name=Microsoft Sans Serif, Size=8,25, Units=3, GdiCharSet=0, GdiVerticalFont=False]
>SystemFonts.MessageBoxFont = [Font: Name=Segoe UI, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False]

with 100% scaling and

>TestRunnerControl.Font = [Font: Name=Microsoft Sans Serif, Size=8, Units=3, GdiCharSet=0, GdiVerticalFont=False]
>TestRunnerControl.Parent....Font = [Font: Name=Microsoft Sans Serif, Size=8, Units=3, GdiCharSet=0, GdiVerticalFont=False]
>Control.DefaultFont = [Font: Name=Microsoft Sans Serif, Size=8, Units=3, GdiCharSet=0, GdiVerticalFont=False]
>SystemFonts.MessageBoxFont = [Font: Name=Segoe UI, Size=9, Units=3, GdiCharSet=1, GdiVerticalFont=False]

with 150% scaling.

Could you check out that branch and tell me the debug output on your machine, please?

  [font-issue]: https://github.com/PoByBolek/PmlUnit/tree/font-issue

**Comment by yang827** [comment]
You're right. This problem is caused by the default font of the Chinese operating system. Unlike the western operating system, the dpi change does not affect the font size.

with 150% scaling.

![150](https://user-images.githubusercontent.com/23608096/81711466-4b7a2700-94a6-11ea-81cc-e8d28c6d4753.PNG)

with 100% scaling

![100](https://user-images.githubusercontent.com/23608096/81711566-6056ba80-94a6-11ea-8981-fc13c022bb5d.PNG)

**Comment by PoByBolek** [comment]
fixed in 747ecd04be9e553a0deaf3cd53c7c9251304f4c2
